
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "The portal rejects you. Perhaps there's another way?"
	#Title for the Advancements
	craftedmessage = "%dim% Unlocked!"
	#Description for the Advancements
	description = "Obtain a %item%"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "minecraft:stone_sword"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,minecraft:the_end"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,End"

